// EuroCompra — Busca em Lojas v2: botão Buscar no mesmo campo + categoria exclusiva de chocolates.
(function(){
  const lojas={'Zara':'https://www.zara.com/be/','H&M':'https://www2.hm.com/en_be/index.html','C&A':'https://www.c-and-a.com/be/en/shop','Primark':'https://www.primark.com/en-be','Mango':'https://shop.mango.com/be/en','Uniqlo':'https://www.uniqlo.com/be/en/','Decathlon':'https://www.decathlon.be/','Carolina Herrera':'https://www.carolinaherrera.com/be/en/','Nike':'https://www.nike.com/be/','Adidas':'https://www.adidas.be/','Foot Locker':'https://www.footlocker.be/','Sephora':'https://www.sephora.be/','Douglas':'https://www.douglas.be/','ICI PARIS XL':'https://www.iciparisxl.be/','MediaMarkt':'https://www.mediamarkt.be/','Coolblue':'https://www.coolblue.be/','Apple':'https://www.apple.com/be/','Fnac':'https://www.nl.fnac.be/','Krëfel':'https://www.krefel.be/','IKEA':'https://www.ikea.com/be/en/','Action':'https://www.action.com/en-be/','JYSK':'https://jysk.be/','CASA':'https://www.casashops.com/en-be/','Maisons du Monde':'https://www.maisonsdumonde.com/BE/en/','Carrefour':'https://www.carrefour.be/','Delhaize':'https://www.delhaize.be/','Colruyt':'https://www.colruyt.be/','DreamLand':'https://www.dreamland.be/','LEGO':'https://www.lego.com/en-be/','Standaard Boekhandel':'https://www.standaardboekhandel.be/','Tom&Co':'https://www.tomandco.com/','Maxi Zoo':'https://www.maxizoo.be/','Louis Vuitton':'https://be.louisvuitton.com/'};
  const chocolates={'Neuhaus':'https://www.neuhauschocolates.com/be_en/','Leonidas':'https://www.leonidas.com/be_en','Pierre Marcolini':'https://eu.marcolini.com/','Galler':'https://www.galler.com/','Chocolaterie Mary':'https://www.mary.be/','Wittamer':'https://wittamer.com/'};
  const grupos={Moda:['Zara','H&M','C&A','Primark','Mango','Uniqlo'],Eletrônicos:['MediaMarkt','Coolblue','Apple','Fnac','Krëfel'],Casa:['IKEA','Action','JYSK','CASA','Maisons du Monde'],Doces:Object.keys(chocolates)};
  const norm=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
  const esc=v=>String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const css='margin:0 0 12px;padding:16px 0;border-bottom:1px solid #e7ebf2';
  function resultado(nome,url){return '<div style="'+css+'"><div style="font-size:17px;font-weight:800;color:#06245c;margin-bottom:4px">'+esc(nome)+'</div><div style="font-size:12px;color:#667085;margin-bottom:10px">Site oficial</div><a href="'+url+'" target="_blank" rel="noopener noreferrer" style="display:inline-flex;align-items:center;justify-content:center;background:#063b9e;color:#fff;border:0;border-radius:10px;padding:10px 15px;font-weight:800;text-decoration:none;line-height:1">🌐 Abrir site oficial</a></div>';}
  function mostrarLista(box,key){const lista=(grupos[key]||[]).map(n=>[n,key==='Doces'?chocolates[n]:lojas[n]]).filter(x=>x[1]);let old=box.querySelector('[data-categoria-lista="'+key+'"]');if(old){old.remove();return;}const div=document.createElement('div');div.className='lojas-lista-aberta ativa';div.dataset.categoriaLista=key;div.style.cssText='grid-column:1/-1;background:#fff;border:1px solid #e2e7f0;border-radius:18px;padding:20px;margin-top:0;box-shadow:0 10px 30px rgba(6,59,158,.06)';div.innerHTML='<div style="font-size:18px;font-weight:800;color:#06245c;margin-bottom:4px">'+esc(key)+'</div><div style="font-size:13px;color:#667085;margin-bottom:4px">Sites oficiais</div>'+lista.map(x=>resultado(x[0],x[1])).join('');box.appendChild(div);}
  function init(){
    const input=document.getElementById('busca-lojas'),box=document.querySelector('.lojas-categorias');if(!input||!box)return;
    if(!box.querySelector('[data-categoria="doces"]')){const card=document.createElement('div');card.className='loja-card';card.dataset.categoria='doces';card.innerHTML='<h3>🍫 Doces</h3><p>Somente lojas de chocolate na Bélgica.</p>';box.appendChild(card);}
    box.querySelectorAll('.loja-card').forEach(card=>{if(card.dataset.formatado==='1')return;card.dataset.formatado='1';card.addEventListener('click',e=>{if(e.target.closest('a'))return;const h=card.querySelector('h3');if(!h)return;const key=h.textContent.replace(/^[^A-Za-zÀ-ÿ]+/,'').trim();mostrarLista(box,key);});});
    const wrap=input.parentElement;let btn=document.getElementById('buscarLojasBtn');if(!btn){wrap.style.display='flex';wrap.style.gap='8px';wrap.style.alignItems='stretch';input.style.flex='1';input.style.minWidth='0';btn=document.createElement('button');btn.id='buscarLojasBtn';btn.type='button';btn.className='btn primary';btn.textContent='🔎 Buscar';btn.style.whiteSpace='nowrap';btn.style.padding='13px 16px';wrap.appendChild(btn);}
    let resultados=document.getElementById('lojasResultados');if(!resultados){resultados=document.createElement('div');resultados.id='lojasResultados';resultados.style.cssText='display:none;grid-column:1/-1;background:#fff;border:1px solid #e2e7f0;border-radius:18px;padding:20px;margin-top:0;box-shadow:0 10px 30px rgba(6,59,158,.06)';box.appendChild(resultados);}
    function buscar(){const q=input.value.trim();if(!q){input.focus();return;}const chave=norm(q);const base=Object.entries(lojas).concat(Object.entries(chocolates));const encontrados=base.filter(([nome])=>norm(nome).includes(chave)||chave.includes(norm(nome)));resultados.style.display='block';resultados.innerHTML=encontrados.length?'<div style="font-size:18px;font-weight:800;color:#06245c;margin-bottom:4px">Resultado da busca</div><div style="font-size:13px;color:#667085;margin-bottom:4px">Sites oficiais</div>'+encontrados.map(x=>resultado(x[0],x[1])).join(''):'<div style="font-weight:800;color:#06245c">Loja não encontrada</div><div style="color:#667085;margin-top:5px">Digite o nome de uma loja ou marca.</div>';}
    btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();buscar();});input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();buscar();}});
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
